name: modcompraoportunidad
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cppad=20240000.5
  - glpk=5.0
  - intel-openmp=2024.2.0
  - ipopt=3.14.16
  - libblas=3.9.0
  - libffi=3.4.4
  - libflang=5.0.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-meta=5.0.0
  - metis=5.1.0
  - mkl=2024.1.0
  - mpfr=4.2.1
  - mpir=3.0.0
  - mumps-seq=5.7.2
  - openmp=5.0.0
  - openssl=3.3.1
  - pcre2=10.44
  - pip=24.0
  - ply=3.11
  - pthreads-win32=2.9.1
  - pyomo=6.7.3
  - python=3.8.19
  - python_abi=3.8
  - scip=9.1.0
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tbb=2021.12.0
  - ucrt=10.0.22621.0
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  - pip:
      - altair==5.3.0
      - attrs==23.2.0
      - blinker==1.8.2
      - cachetools==5.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.7
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - numpy==1.24.4
      - packaging==24.1
      - pandas==2.0.3
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.22.0
      - protobuf==5.27.2
      - pyarrow==17.0.0
      - pydeck==0.9.1
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.19.0
      - scipy==1.10.1
      - six==1.16.0
      - smmap==5.0.1
      - streamlit==1.36.0
      - tenacity==8.5.0
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.4.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - watchdog==4.0.1
      - zipp==3.19.2
